name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main  #trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t fastapi-app .
          docker tag fastapi-app ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/fastapi-app:latest
          docker push ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/fastapi-app:latest

      - name: Deploy FastAPI to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fastapi-app
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: ${{ secrets.AZURE_REGISTRY_USERNAME }}.azurecr.io/fastapi-app:latest